# Generated by Django 5.0.7 on 2024-07-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='total',
            new_name='total_htva',
        ),
    ]
