# Generated by Django 5.0.7 on 2024-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_htva',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
