# Generated by Django 5.0.7 on 2024-07-29 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_rename_total_facture_total_htva'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
