# Generated by Django 5.0.7 on 2024-07-26 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 26, 9, 41, 46, 903408, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
