# Generated by Django 5.0.7 on 2024-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_htva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
