# Generated by Django 5.0.7 on 2024-08-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_ligne_htva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
            ],
        ),
    ]
